services:
  - type: web
    name: pdf-flattener
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libmupdf-dev && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free 