name: Build Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyPDF2 tkinter

      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed flatten_pdf.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Flattener-${{ matrix.os }}
          path: dist/*
