name: Build Executable

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # This will trigger on any tag starting with 'v'
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build executable
      run: pyinstaller --onefile --windowed flatten_pdf.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: flatten_pdf-${{ runner.os }}
        path: |
          dist/flatten_pdf.exe
          dist/flatten_pdf

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/flatten_pdf.exe
          dist/flatten_pdf
        draft: false
        prerelease: false
        generate_release_notes: true
